### ISSUE TITLE
[Question] How to Copy Whole Folders Without Interpolation?

### ISSUE THREAD

**Issue by Jean-Baptiste-Lasselle** [manuth/ExtendedYoGenerator#3]
Hi, thank you so much for your package ! :) 

I started using it, and I have a question : 
* how can I specify to "just copy an entire folder from the templates/ forlder", without interpolation ? 
* I 'm a beginner with yeoman, so don't hesitate telling me I am trying to do something which does not make sense...

Thank you so much, I really did not want to do yeoman without typescript ! :)

**Comment by manuth** [comment]
Alright - as you have noticed, you can copy files from your templates-folder using `FileMappings` as seen in your project:
https://github.com/gravitee-lab/generator-orbinoid/blob/861020603c2a98ff17650e9fee2dc9349242032f/src/generators/app/AppGenerator.ts#L149-L161

This works the same way for folders. If you want to copy a folder simply pass a file-mapping like this:
```ts
import { join } from "path";
// [...]
                            FileMappings: [
                                {
                                    Source: join("{{ Path to your folder (example: '.vscode' }}"),
                                    Context: (settings) =>
                                    {
                                        return { mySetting: true };
                                    },
                                    Destination: "{{ Name of the folder to create (example: '.vscode')"
                                }
                            ]
```

If you provide a `Context`, each file will be interpolated. Preventing interpolation is as simple as just removing the `Context`-part:

```ts
                            FileMappings: [
                                {
                                    Source: join("settings", "vscode"),
                                    Destination: ".vscode"
                                }
                            ]
```

**Comment by manuth** [comment]
Also, looking at your project, I would recommend you to recreate your project using the latest version of [manuth/TSProjectGenerator](https://github.com/manuth/TSProjectGenerator.git) as this one is way more stable and brings a lot of new features such as:
  - Linting using `eslint` instead of `tslint` out of the box
  - Buletproof API for extending existing generators
  - The option to add `FileMappings` directly to the generator instead of having to add components

**Comment by Jean-Baptiste-Lasselle** [comment]
Hi @manuth ,

Thank you so very much for this comprehensive work after my question ! 

* I will try as soon as possible your suggestion as to how to copy an entire folder, using a `FileMappings`, and also thank you about your suggestion to use an up-to-date version  of [manuth/TSProjectGenerator](https://github.com/manuth/TSProjectGenerator.git)
* In the project I am working on, I had to leave aside my work on the yeoman generator, to finish up other prioritized tasks in my company : 
  * to give you a bit more details, I am leading the CI CD complete redesign for my company
  * In that context, I work with Circle CI
  * And with Circle CI, one of the components is _"Circle CI Orbs"_
  * Now, to develop and maintain Circle CI Orbs, Circle CI provides "Circle CI CLI": this tool provides CLI commands, like `init`, `pack`, `validate`, `publish`... :  Circle CI `Orb`s, sort have a "source code", made of yaml, packing them is sort of a compilation, and publishing them is making them available to anyone, through a "Circle CI Orb Registry. Also note in a typical Orb source code project, you will find a "test" folder.
  * Alright, now to sum you up all this, I understood, that just like any npm (or any software today), Circle CI Orbs have a "development lifecycle". And the "Circle CI CLI", I immediately noticed, is so much less experienced at managing such a development lifecycle, than ... npm. Which is why I created ["the Orbinoid"](https://github.com/gravitee-lab/orbinoid/tree/develop), the idea being that one can rely on all the power, and experience of npm / nodejs to manage the development lifecycle of Circle CI Orbs. 
  * Now, i began  working on a yeoman generator, to replace the Circle CI CLI init command, which is : 
    * to begin with, bugged : https://github.com/CircleCI-Public/circleci-cli/issues/491
    * and so much less experienced and powerful, compared to yeoman generators, when it comes to "initializing the source code of a project", features ... And now you know where, and why your generator was useful : we are going to show the Circle CI Team how Open Source will always  be infinitely more powerful than any closed source software, Like Circle CI... Out of being nice to them :)


Alright, I will give you news as soon as I have managed to spend a few more hours on the yeoman generator, and will soon, thanks to the energy you gave me with this big work that you did on your side.

I support you in keeping working on this yeoman generator, which already helped me a lot, and should become even more well known in the community. By the way, if you would like to have a nice project website, with documentation etc... I could n would help there, so let me know about that :) 

Be sure that I will give full feed backright after that, and will then reveal you another project, GNU Affero GPLv3 I am working on, related to CI CD, for my company https://github.com/gravitee-io

:)

**Comment by manuth** [comment]
At this point I'd like to note, that this project is merely an extension to the great [yeoman/generator](https://github.com/yeoman/generator). It's supposed to make creating and inheriting generators easier.
Having this out of the way, let's talk about the website.

This really sounds quite interesting as I was feeling a bit uneasy about working with PHP again even though SilverStripe really is a great framework.

Let's do the further talking through E-mail or Discord.
Thanks for taking the time 😄

**Comment by Jean-Baptiste-Lasselle** [comment]
Hi again @manuth :) 

* sure the great yeoman project has a lot of work done here, your project is "just another generator", for this project
* never the less, I wanted to use yeoman, I knew that, but I had a requirement : to work in pure TypeScript. And when I started to look for a generator generator, or typescript, well very few results appeared, and finally selected yours as the most rigourous reliable one.
* So yes, "its just generator", yet, it is very valuable,and answers a need that I believe, many have too... to say it in other words, your work might be a lot more valuable than what it seems  : I believe many people, in many projects, have thought of developing a generator, and really want to work pure `TypeScript`, and therefore have given up yeoman for webpack (and ended up in a mess of complexity), or completely have given up their generator idea. I think there is something, with your Typescript generator generator, a something worth a better website, better documentation, and long term support
* sending you any email in the next minutes , with discord server invitation :)
